name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build -t commitcrew/ca3:latest .
        docker images  # Optional: List Docker images for verification

    - name: Run Docker container
      run: |
        docker run -d --name my_container commitcrew/ca3:latest
